#!/bin/bash

echo "Running post-commit hook" >> post-commit.log

./update_combined_code.sh

# Check if there are changes to combined_code.txt
if git diff --exit-code combined_code.txt; then
    echo "No changes to combined_code.txt" >> post-commit.log
else
    echo "Changes detected in combined_code.txt" >> post-commit.log
    git add combined_code.txt
    echo "combined_code.txt updated after commit" >> post-commit.log
fi

echo "Post-commit hook completed" >> post-commit.log