version: '3.8'

services:
  server:
    build:
      context: .
      args:
        ENV: ${ENV:-production}
    environment:
      NODE_ENV: ${ENV:-production}
      PORT: 5000
      NEO_4J_LEDGER_SPACE_BOLT_URL: ${NEO_4J_LEDGER_SPACE_BOLT_URL}
      NEO_4J_LEDGER_SPACE_USER: ${NEO_4J_LEDGER_SPACE_USER}
      NEO_4J_LEDGER_SPACE_PASS: ${NEO_4J_LEDGER_SPACE_PASS}
      NEO_4J_SEARCH_SPACE_BOLT_URL: ${NEO_4J_SEARCH_SPACE_BOLT_URL}
      NEO_4J_SEARCH_SPACE_USER: ${NEO_4J_SEARCH_SPACE_USER}
      NEO_4J_SEARCH_SPACE_PASS: ${NEO_4J_SEARCH_SPACE_PASS}
      OPEN_EXCHANGE_RATES_API: ${OPEN_EXCHANGE_RATES_API}
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  cloudwatch-agent:
    image: amazon/cloudwatch-agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AWS_REGION: ${AWS_REGION:-us-east-1}
    profiles:
      - aws