import express from 'express';
import { validateRequest } from '../../../middleware/validateRequest';
import { verifyClientApiKey } from '../../../middleware/clientApiKeyAuth';
import { validateUUID, validatePhone } from '../../../utils/validators';
import { sanitizeUUID, sanitizePhone } from '../../../utils/inputSanitizer';
import { VerificationPurpose } from '../services/verification/types';
import { storeOTP, validateChatbotOTP } from '../controllers/otpStoreController';
import { checkOTPVerificationStatus } from '../controllers/otpVerificationStatusController';

export default function otpStoreRoutes() {
  const router = express.Router();

  // Request schemas
  const storeOTPSchema = {
    memberID: {
      sanitizer: sanitizeUUID,
      validator: validateUUID,
      required: true
    },
    phone: {
      sanitizer: sanitizePhone,
      validator: validatePhone,
      required: true
    },
    otp: {
      sanitizer: sanitizePhone, // Using phone sanitizer as it removes non-digits
      validator: (otp: string) => ({
        isValid: /^\d{6}$/.test(otp),
        message: otp.length !== 6 ? 'OTP must be 6 digits' : 'Valid OTP'
      }),
      required: true
    },
    purpose: {
      sanitizer: (value: string) => value?.toUpperCase() as VerificationPurpose,
      validator: (value: string) => ({
        isValid: value === 'PASSWORD_RESET',
        message: 'Purpose must be PASSWORD_RESET'
      }),
      required: true
    }
  };

  const validateChatbotOTPSchema = {
    phone: {
      sanitizer: sanitizePhone,
      validator: validatePhone,
      required: true
    },
    otp: {
      sanitizer: sanitizePhone, // Using phone sanitizer as it removes non-digits
      validator: (otp: string) => ({
        isValid: /^\d{6}$/.test(otp),
        message: otp.length !== 6 ? 'OTP must be 6 digits' : 'Valid OTP'
      }),
      required: true
    },
    source: {
      sanitizer: (value: string) => value,
      validator: (value: string) => ({
        isValid: value === 'chatbot',
        message: 'Source must be chatbot'
      }),
      required: true
    }
  };

  /**
   * @swagger
   * /verify/storeOtp:
   *   post:
   *     tags: [Members]
   *     summary: Store app-generated OTP
   *     description: Stores an OTP generated by the app for later verification via WhatsApp
   *     requestBody:
   *       required: true
   *       content:
   *         application/json:
   *           schema:
   *             type: object
   *             required:
   *               - memberID
   *               - phone
   *               - otp
   *               - purpose
   *             properties:
   *               memberID:
   *                 type: string
   *                 format: uuid
   *                 description: Member ID
   *               phone:
   *                 type: string
   *                 pattern: ^\+?[1-9]\d{1,14}$
   *                 description: Phone number associated with the member
   *               otp:
   *                 type: string
   *                 pattern: ^\d{6}$
   *                 description: 6-digit OTP generated by the app
   *               purpose:
   *                 type: string
   *                 enum: [PASSWORD_RESET]
   *                 description: Purpose of OTP verification (must be PASSWORD_RESET)
   *     responses:
   *       200:
   *         description: OTP stored successfully
   *         content:
   *           application/json:
   *             schema:
   *               type: object
   *               properties:
   *                 message:
   *                   type: string
   *                   example: OTP stored successfully
   *                 data:
   *                   type: object
   *                   properties:
   *                     action:
   *                       type: object
   *                       properties:
   *                         id:
   *                           type: string
   *                           format: uuid
   *                         type:
   *                           type: string
   *                           enum: [MEMBER_UPDATE]
   *                         timestamp:
   *                           type: string
   *                           format: date-time
   *                         actor:
   *                           type: string
   *                           format: uuid
   *                         details:
   *                           type: object
   *                           properties:
   *                             memberID:
   *                               type: string
   *                               format: uuid
   *                             phone:
   *                               type: string
   *                             expiresIn:
   *                               type: number
   *                               description: OTP expiry in seconds
   */
  router.post('/storeOtp', verifyClientApiKey, validateRequest(storeOTPSchema), storeOTP);

  /**
   * @swagger
   * /verify/validateChatbotOtp:
   *   post:
   *     tags: [Members]
   *     summary: Validate OTP from chatbot
   *     description: Validates an OTP received from the chatbot
   *     requestBody:
   *       required: true
   *       content:
   *         application/json:
   *           schema:
   *             type: object
   *             required:
   *               - phone
   *               - otp
   *               - source
   *             properties:
   *               phone:
   *                 type: string
   *                 pattern: ^\+?[1-9]\d{1,14}$
   *                 description: Phone number that sent the OTP
   *               otp:
   *                 type: string
   *                 pattern: ^\d{6}$
   *                 description: 6-digit OTP received from the user
   *               source:
   *                 type: string
   *                 enum: [chatbot]
   *                 description: Source of the verification request
   *     responses:
   *       200:
   *         description: OTP verified successfully
   *         content:
   *           application/json:
   *             schema:
   *               type: object
   *               properties:
   *                 message:
   *                   type: string
   *                   example: OTP verified successfully
   *                 data:
   *                   type: object
   *                   properties:
   *                     action:
   *                       type: object
   *                       properties:
   *                         id:
   *                           type: string
   *                           format: uuid
   *                         type:
   *                           type: string
   *                           enum: [MEMBER_UPDATE]
   *                         timestamp:
   *                           type: string
   *                           format: date-time
   *                         actor:
   *                           type: string
   *                           format: uuid
   *                         details:
   *                           type: object
   *                           properties:
   *                             memberID:
   *                               type: string
   *                               format: uuid
   *                             otpVerified:
   *                               type: boolean
   *                               example: true
   *                             source:
   *                               type: string
   *                               example: chatbot
   */
  router.post('/validateChatbotOtp', verifyClientApiKey, validateRequest(validateChatbotOTPSchema), validateChatbotOTP);

  /**
   * @swagger
   * /verify/checkOtpStatus:
   *   get:
   *     tags: [Members]
   *     summary: Check OTP verification status
   *     description: Checks if an OTP has been verified for a given phone number
   *     parameters:
   *       - in: query
   *         name: phone
   *         required: true
   *         schema:
   *           type: string
   *           pattern: ^\+?[1-9]\d{1,14}$
   *         description: Phone number to check verification status for
   *     responses:
   *       200:
   *         description: OTP verification status retrieved
   *         content:
   *           application/json:
   *             schema:
   *               type: object
   *               properties:
   *                 message:
   *                   type: string
   *                   example: OTP verification status retrieved
   *                 data:
   *                   type: object
   *                   properties:
   *                     action:
   *                       type: object
   *                       properties:
   *                         id:
   *                           type: string
   *                           format: uuid
   *                         type:
   *                           type: string
   *                           enum: [MEMBER_UPDATE]
   *                         timestamp:
   *                           type: string
   *                           format: date-time
   *                         actor:
   *                           type: string
   *                           format: uuid
   *                         details:
   *                           type: object
   *                           properties:
   *                             memberID:
   *                               type: string
   *                               format: uuid
   *                             phone:
   *                               type: string
   *                             verified:
   *                               type: boolean
   *                               example: true
   *                             verifiedAt:
   *                               type: string
   *                               format: date-time
   *                               nullable: true
   */
  router.get('/checkOtpStatus', verifyClientApiKey, checkOTPVerificationStatus);

  return router;
}
