name: Deploy Connectors

on:
  workflow_dispatch:

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/prod' && 'production' || github.ref == 'refs/heads/stage' && 'staging' || 'development' }}

    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/prod' && 'production' || github.ref == 'refs/heads/stage' && 'staging' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: af-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init and Apply
        env:
          TF_VAR_environment: ${{ env.ENVIRONMENT }}
          TF_VAR_create_ecr: "true"
          TF_VAR_create_ecs_cluster: "true"
          TF_VAR_create_log_group: "true"
          TF_VAR_create_key_pair: "true"
          TF_VAR_create_iam_roles: "true"
          TF_VAR_create_load_balancer: "true"
          TF_VAR_create_target_group: "true"
          TF_VAR_create_security_groups: "true"
          TF_VAR_create_neo4j_instances: "true"
        run: |
          cd terraform
          echo "Initializing Terraform..."
          terraform init

          echo "Applying Terraform changes..."
          terraform apply -auto-approve -input=false

          echo "Terraform apply completed successfully"

      - name: Get Infrastructure Outputs
        run: |
          cd terraform
          echo "Retrieving infrastructure outputs..."
          terraform output || { echo "Failed to retrieve Terraform outputs"; exit 1; }
          echo "VPC_ID=$(terraform output -raw vpc_id)" >> $GITHUB_ENV || true
          echo "SUBNET_IDS=$(terraform output -raw subnet_ids)" >> $GITHUB_ENV || true
          echo "NEO4J_SECURITY_GROUP_ID=$(terraform output -raw neo4j_security_group_id)" >> $GITHUB_ENV || true
          echo "KEY_PAIR_NAME=$(terraform output -raw key_pair_name)" >> $GITHUB_ENV || true
          echo "ALB_SECURITY_GROUP_ID=$(terraform output -raw alb_security_group_id)" >> $GITHUB_ENV || true
          echo "ECS_TASKS_SECURITY_GROUP_ID=$(terraform output -raw ecs_tasks_security_group_id)" >> $GITHUB_ENV || true
          echo "ALB_DNS_NAME=$(terraform output -raw alb_dns_name)" >> $GITHUB_ENV || true
          echo "TARGET_GROUP_ARN=$(terraform output -raw target_group_arn)" >> $GITHUB_ENV || true

      - name: Print Infrastructure Information
        run: |
          echo "Infrastructure deployed for the ${{ env.ENVIRONMENT }} environment:"
          echo "VPC_ID: ${{ env.VPC_ID }}"
          echo "SUBNET_IDS: ${{ env.SUBNET_IDS }}"
          echo "NEO4J_SECURITY_GROUP_ID: ${{ env.NEO4J_SECURITY_GROUP_ID }}"
          echo "KEY_PAIR_NAME: ${{ env.KEY_PAIR_NAME }}"
          echo "ALB_SECURITY_GROUP_ID: ${{ env.ALB_SECURITY_GROUP_ID }}"
          echo "ECS_TASKS_SECURITY_GROUP_ID: ${{ env.ECS_TASKS_SECURITY_GROUP_ID }}"
          echo "ALB_DNS_NAME: ${{ env.ALB_DNS_NAME }}"
          echo "TARGET_GROUP_ARN: ${{ env.TARGET_GROUP_ARN }}"
