name: Deploy Databases

on:
  workflow_dispatch:

jobs:
  deploy_neo4j:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_reinstall == 'REINSTALL'
    environment: ${{ github.ref == 'refs/heads/prod' && 'production' || github.ref == 'refs/heads/stage' && 'staging' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        env:
          TF_VAR_environment: ${{ env.ENVIRONMENT }}
          TF_VAR_create_neo4j_instances: true
          TF_VAR_create_ecr: false
          TF_VAR_create_ecs_cluster: false
          TF_VAR_create_log_group: false
          TF_VAR_create_iam_roles: false
          TF_VAR_create_key_pair: false
          TF_VAR_create_load_balancer: false
          TF_VAR_create_target_group: false
          TF_VAR_create_security_groups: false
        run: |
          cd terraform
          terraform workspace select ${{ env.ENVIRONMENT }} || terraform workspace new ${{ env.ENVIRONMENT }}
          terraform apply -auto-approve

      - name: Print Neo4j Information
        run: |
          cd terraform
          echo "Neo4j Information for ${{ env.ENVIRONMENT }} environment:"
          echo "----------------------------------------"
          echo "NEO4J_LEDGER_SPACE_BOLT_URL: $(terraform output -raw neo4j_ledger_space_bolt_url)"
          echo "NEO4J_SEARCH_SPACE_BOLT_URL: $(terraform output -raw neo4j_search_space_bolt_url)"
          echo "NEO4J_LEDGER_SPACE_USERNAME: $(terraform output -raw neo4j_ledger_space_username)"
          echo "NEO4J_SEARCH_SPACE_USERNAME: $(terraform output -raw neo4j_search_space_username)"
          echo "NEO4J_LEDGER_SPACE_PASSWORD: $(terraform output -raw neo4j_ledger_space_password)"
          echo "NEO4J_SEARCH_SPACE_PASSWORD: $(terraform output -raw neo4j_search_space_password)"
          echo "----------------------------------------"
          echo "NEO4J_PRIVATE_KEY:"
          terraform output -raw neo4j_private_key
          echo "----------------------------------------"
          echo "Please save these values securely. You may need to manually set them as GitHub secrets or use them in your application configuration."
