name: Deploy Databases

on:
  workflow_dispatch:
    inputs:
      confirm_reinstall:
        description: 'Type "REINSTALL" to confirm database reinstallation'
        required: true

jobs:
  deploy_neo4j:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_reinstall == 'REINSTALL'
    environment: ${{ github.ref == 'refs/heads/prod' && 'production' || github.ref == 'refs/heads/stage' && 'staging' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        env:
          TF_VAR_environment: ${{ env.ENVIRONMENT }}
          TF_VAR_create_ecr: false
          TF_VAR_create_ecs_cluster: false
          TF_VAR_create_log_group: false
        run: |
          cd terraform
          terraform workspace select ${{ env.ENVIRONMENT }} || terraform workspace new ${{ env.ENVIRONMENT }}
          terraform apply -auto-approve

      - name: Get Neo4j Information
        run: |
          cd terraform
          echo "Terraform outputs:"
          terraform output || echo "No outputs found"

          NEO_4J_LEDGER_SPACE_BOLT_URL=$(terraform output -raw neo4j_ledger_space_bolt_url)
          NEO_4J_SEARCH_SPACE_BOLT_URL=$(terraform output -raw neo4j_search_space_bolt_url)
          NEO_4J_PRIVATE_KEY=$(terraform output -raw neo4j_private_key)
          NEO_4J_LEDGER_SPACE_USERNAME=$(terraform output -raw neo4j_ledger_space_username)
          NEO_4J_SEARCH_SPACE_USERNAME=$(terraform output -raw neo4j_search_space_username)
          NEO_4J_LEDGER_SPACE_PASSWORD=$(terraform output -raw neo4j_ledger_space_password)
          NEO_4J_SEARCH_SPACE_PASSWORD=$(terraform output -raw neo4j_search_space_password)

          echo "NEO_4J_LEDGER_SPACE_BOLT_URL=$NEO_4J_LEDGER_SPACE_BOLT_URL" >> $GITHUB_ENV
          echo "NEO_4J_SEARCH_SPACE_BOLT_URL=$NEO_4J_SEARCH_SPACE_BOLT_URL" >> $GITHUB_ENV
          echo "NEO_4J_PRIVATE_KEY=$NEO_4J_PRIVATE_KEY" >> $GITHUB_ENV
          echo "NEO_4J_LEDGER_SPACE_USERNAME=$NEO_4J_LEDGER_SPACE_USERNAME" >> $GITHUB_ENV
          echo "NEO_4J_SEARCH_SPACE_USERNAME=$NEO_4J_SEARCH_SPACE_USERNAME" >> $GITHUB_ENV
          echo "NEO_4J_LEDGER_SPACE_PASSWORD=$NEO_4J_LEDGER_SPACE_PASSWORD" >> $GITHUB_ENV
          echo "NEO_4J_SEARCH_SPACE_PASSWORD=$NEO_4J_SEARCH_SPACE_PASSWORD" >> $GITHUB_ENV

      - name: Save Neo4j Information to GitHub Secrets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh secret set NEO_4J_LEDGER_SPACE_BOLT_URL --body "$NEO_4J_LEDGER_SPACE_BOLT_URL" --env ${{ env.ENVIRONMENT }}
          gh secret set NEO_4J_SEARCH_SPACE_BOLT_URL --body "$NEO_4J_SEARCH_SPACE_BOLT_URL" --env ${{ env.ENVIRONMENT }}
          gh secret set NEO_4J_PRIVATE_KEY --body "$NEO_4J_PRIVATE_KEY" --env ${{ env.ENVIRONMENT }}
          gh secret set NEO_4J_LEDGER_SPACE_USERNAME --body "$NEO_4J_LEDGER_SPACE_USERNAME" --env ${{ env.ENVIRONMENT }}
          gh secret set NEO_4J_SEARCH_SPACE_USERNAME --body "$NEO_4J_SEARCH_SPACE_USERNAME" --env ${{ env.ENVIRONMENT }}
          gh secret set NEO_4J_LEDGER_SPACE_PASSWORD --body "$NEO_4J_LEDGER_SPACE_PASSWORD" --env ${{ env.ENVIRONMENT }}
          gh secret set NEO_4J_SEARCH_SPACE_PASSWORD --body "$NEO_4J_SEARCH_SPACE_PASSWORD" --env ${{ env.ENVIRONMENT }}
