name: Remove Databases

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to remove databases from'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - staging
        - production

jobs:
  remove_databases:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
        cd terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Destroy
        env:
          TF_VAR_environment: ${{ env.ENVIRONMENT }}
        run: |
          cd terraform
          terraform workspace select ${{ env.ENVIRONMENT }} || echo "Workspace ${{ env.ENVIRONMENT }} not found, proceeding with default"
          terraform destroy -auto-approve

      - name: Remove GitHub Secrets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh secret remove NEO_4J_LEDGER_SPACE_BOLT_URL --env ${{ env.ENVIRONMENT }}
          gh secret remove NEO_4J_SEARCH_SPACE_BOLT_URL --env ${{ env.ENVIRONMENT }}
          gh secret remove NEO_4J_PRIVATE_KEY --env ${{ env.ENVIRONMENT }}
          gh secret remove NEO_4J_LEDGER_SPACE_USERNAME --env ${{ env.ENVIRONMENT }}
          gh secret remove NEO_4J_SEARCH_SPACE_USERNAME --env ${{ env.ENVIRONMENT }}
          gh secret remove NEO_4J_LEDGER_SPACE_PASSWORD --env ${{ env.ENVIRONMENT }}
          gh secret remove NEO_4J_SEARCH_SPACE_PASSWORD --env ${{ env.ENVIRONMENT }}

      - name: Confirmation
        run: |
          echo "Database resources have been removed for the ${{ env.ENVIRONMENT }} environment."
          echo "GitHub secrets related to Neo4j have been deleted."
