name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        type: choice
        options:
          - development
          - staging
          - production
      run_cleanup:
        description: "Run cleanup of orphaned resources after deployment"
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      TF_VAR_aws_region: af-south-1
      TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
      TF_VAR_whatsapp_bot_api_key: ${{ secrets.WHATSAPP_BOT_API_KEY }}
      TF_VAR_open_exchange_rates_api: ${{ secrets.OPEN_EXCHANGE_RATES_API }}
      TF_VAR_neo4j_ledger_space_user: ${{ secrets.NEO4J_LEDGER_SPACE_USER }}
      TF_VAR_neo4j_ledger_space_pass: ${{ secrets.NEO4J_LEDGER_SPACE_PASS }}
      TF_VAR_neo4j_search_space_user: ${{ secrets.NEO4J_SEARCH_SPACE_USER }}
      TF_VAR_neo4j_search_space_pass: ${{ secrets.NEO4J_SEARCH_SPACE_PASS }}
      TF_VAR_neo4j_enterprise_license: ${{ secrets.NEO4J_ENTERPRISE_LICENSE }}
      TF_VAR_neo4j_public_key: ${{ secrets.NEO4J_PUBLIC_KEY }}
      TF_VAR_neo4j_ledger_space_bolt_url: ${{ secrets.NEO4J_LEDGER_SPACE_BOLT_URL }}
      TF_VAR_neo4j_search_space_bolt_url: ${{ secrets.NEO4J_SEARCH_SPACE_BOLT_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TF_VAR_aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Debug Environment Variables
        run: |
          echo "Debugging Environment Variables:"
          env | grep TF_VAR_ | sed 's/=.*/=***/'
          echo "AWS_REGION: $AWS_REGION"

      - name: Terraform Version and Validation
        run: |
          cd terraform
          terraform version
          terraform validate

      - name: Terraform Init and Workspace Selection
        run: |
          cd terraform
          terraform init
          terraform workspace select ${{ github.event.inputs.environment }} || terraform workspace new ${{ github.event.inputs.environment }}

      - name: Run Pre-deployment Check
        run: |
          cd terraform
          ./pre_deployment_check.sh

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform
          terraform plan -detailed-exitcode -out=tfplan -input=false || exit_code=$?
          if [ $exit_code -eq 1 ]; then
            echo "Terraform plan failed"
            exit 1
          elif [ $exit_code -eq 2 ]; then
            echo "Terraform plan has changes"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "Terraform plan has no changes"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
          terraform show -no-color tfplan > tfplan.txt

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: terraform/tfplan.txt

      - name: Terraform Apply
        if: steps.plan.outputs.has_changes == 'true'
        run: |
          cd terraform
          terraform apply -auto-approve tfplan

      - name: Get Terraform Outputs
        id: tf-outputs
        run: |
          cd terraform
          echo "Retrieving Terraform outputs..."
          terraform output -json > tf_outputs.json
          echo "tf_outputs=$(cat tf_outputs.json | jq -c .)" >> $GITHUB_OUTPUT

      - name: Deploy Application
        env:
          TF_OUTPUTS: ${{ steps.tf-outputs.outputs.tf_outputs }}
        run: |
          echo "Deploying application to ${{ github.event.inputs.environment }}"
          # Add your deployment commands here

      - name: Run Post-Deployment Tests
        env:
          TF_OUTPUTS: ${{ steps.tf-outputs.outputs.tf_outputs }}
        run: |
          echo "Running post-deployment tests for ${{ github.event.inputs.environment }}"
          # Add your test commands here

      - name: Cleanup Orphaned Resources
        if: github.event.inputs.run_cleanup == 'true'
        run: |
          cd terraform
          ./cleanup_orphaned_resources.sh

      - name: Log Deployment
        if: success()
        run: |
          echo "Deployment to ${{ github.event.inputs.environment }} triggered by ${{ github.actor }} at $(date)" >> deployment_log.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add deployment_log.txt
          git commit -m "Log deployment to ${{ github.event.inputs.environment }}"
          git push

      - name: Notify on Failure
        if: failure()
        run: |
          echo "Deployment to ${{ github.event.inputs.environment }} failed. Please check the logs for more information."
          # Add notification mechanism here (e.g., send an email, Slack message, etc.)
