name: deploy_to_prod
run-name: ${{ github.actor }} pushed to prod_auto_deploy_setup with commit message '${{ github.event.head_commit.message }}'

on: 
  push: 
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        working-directory: .

      # Uncomment if you have tests to run
      # - name: Run tests
      #   run: npm test

      - name: Create .env file
        run: |
          echo "NEO_4J_LEDGER_SPACE_USER=${{ secrets.NEO_4J_LEDGER_SPACE_USER }}" >> .env
          echo "NEO_4J_LEDGER_SPACE_PASS=${{ secrets.NEO_4J_LEDGER_SPACE_PASS }}" >> .env
          echo "NEO_4J_LEDGER_SPACE_BOLT_URL=${{ secrets.NEO_4J_LEDGER_SPACE_BOLT_URL }}" >> .env
          echo "NEO_4J_SEARCH_SPACE_USER_DEV=${{ secrets.NEO_4J_SEARCH_SPACE_USER_DEV }}" >> .env
          echo "NEO_4J_SEARCH_SPACE_PASS_DEV=${{ secrets.NEO_4J_SEARCH_SPACE_PASS_DEV }}" >> .env
          echo "NEO_4J_SEARCH_SPACE_BOLT_URL=${{ secrets.NEO_4J_SEARCH_SPACE_BOLT_URL }}" >> .env
          echo "STAGE=${{ secrets.STAGE }}" >> .env

      - name: Set up SSH deploy keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add EC2 Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Copy Project to EC2
        run: |
          echo "${{ secrets.SSH_KEY }}" > taku263_credex.pem
          chmod 600 taku263_credex.pem
          scp -i taku263_credex.pem -o StrictHostKeyChecking=no -r ./build/* .env package-lock.json ec2-user@${{ secrets.EC2_IP }}:/var/www/html/credex_ec2

      - name: Set ownership on remote server
        run: |
          ssh -i taku263_credex.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} \
          "sudo chown -R ec2-user:www-data /var/www/html/credex_ec2 && sudo chmod -R 755 /var/www/html/credex_ec2"

      - name: Cleanup
        run: |
          rm taku263_credex.pem

      - run: 
          npm ci