name: deploy_to_prod
run-name: ${{ github.actor }} pushed to prod_auto_deploy_setup

on: 
  push: 
    branches:
      - prod_auto_deploy_setup  # Testing branch

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: .

      # For running tests
      # - name: Run tests
      #   run: npm test
      #   working-directory: .

      # - name: Build project
      #   run: npm run build
      #   working-directory: .

      - name: Set up SSH deploy keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to AWS EC2
        run: |
          scp -r -o StrictHostKeyChecking=no ./build ubuntu@${{ secrets.EC2_IP }}:/var/www/html
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}

      - name: Set ownership on remote server
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          # Create known_hosts file if it doesn't exist
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          # Clear old key from known_hosts
          ssh-keygen -R ${{ secrets.EC2_IP }} >> /home/runner/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> /home/runner/.ssh/known_hosts

          # Run the SSH command
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} \
          "sudo chown -R ubuntu:apache /var/www/html/${{ secrets.PROJECT_DIRECTORY }}/ && chmod 777 -R /var/www/html/${{ secrets.PROJECT_DIRECTORY }}/storage && chmod -R 777 /var/www/html/${{ secrets.PROJECT_DIRECTORY }}/bootstrap/cache/ && cd /var/www/html/${{ secrets.PROJECT_DIRECTORY }}/ && sudo npm install -g vite && npm install && sudo chown -R ubuntu:apache /var/www/html/${{ secrets.PROJECT_DIRECTORY }}/ && chmod +x /var/www/html/${{ secrets.PROJECT_DIRECTORY }}/dev_run.sh"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
