name: Deploy Documentation

on:
  workflow_dispatch:

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/prod' && 'production' || github.ref == 'refs/heads/stage' && 'staging' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set Environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "DOMAIN=mycredex.app" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
            echo "DOMAIN=dev.mycredex.dev" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: af-south-1

      - name: Deploy to S3
        run: |
          aws s3 sync docs/ s3://docs.${DOMAIN} \
            --delete

      - name: Print Deployment Information
        run: |
          echo "Documentation deployment completed successfully."
          echo "Environment: $ENVIRONMENT"
          echo "Bucket: docs.${DOMAIN}"
          echo "URL: https://docs.${DOMAIN}"
