name: Wipe AWS Resources

on:
  workflow_dispatch:
    inputs:
      confirm_wipe:
        description: 'Type "YES" to confirm wiping all AWS resources'
        required: true

jobs:
  wipe-aws-resources:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_wipe == 'YES'
    environment: ${{ github.ref == 'refs/heads/prod' && 'production' || github.ref == 'refs/heads/stage' && 'staging' || 'development' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set Environment
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT=development" >> $GITHUB_ENV
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1

    - name: Wipe EC2 Resources
      run: |
        echo "Terminating EC2 instances..."
        instance_ids=$(aws ec2 describe-instances --filters Name=instance-state-name,Values=pending,running,stopping,stopped --query 'Reservations[*].Instances[*].[InstanceId]' --output text)
        if [ -n "$instance_ids" ]; then
          aws ec2 terminate-instances --instance-ids $instance_ids
          echo "Waiting for instances to terminate..."
          aws ec2 wait instance-terminated --instance-ids $instance_ids
        else
          echo "No running instances to terminate."
        fi

        echo "Deleting EC2 security groups..."
        sg_ids=$(aws ec2 describe-security-groups --query 'SecurityGroups[?GroupName!=`default`].[GroupId]' --output text)
        for sg_id in $sg_ids; do
          if ! aws ec2 delete-security-group --group-id $sg_id 2>/dev/null; then
            echo "Failed to delete security group $sg_id. It may have dependencies."
          fi
        done

        echo "Deleting EC2 key pairs..."
        key_pairs=$(aws ec2 describe-key-pairs --query 'KeyPairs[*].[KeyName]' --output text)
        for key in $key_pairs; do
          aws ec2 delete-key-pair --key-name $key
        done

    - name: Wipe VPC Resources
      run: |
        echo "Deleting VPC resources..."
        vpc_ids=$(aws ec2 describe-vpcs --query 'Vpcs[?IsDefault==`false`].[VpcId]' --output text)
        for id in $vpc_ids; do
          aws ec2 delete-vpc --vpc-id $id
        done

    - name: Wipe S3 Buckets
      run: |
        echo "Deleting S3 buckets..."
        buckets=$(aws s3 ls | awk '{print $3}')
        for bucket in $buckets; do
          echo "Processing bucket: $bucket"
          # Remove all versions and delete markers
          versions=$(aws s3api list-object-versions --bucket $bucket --output json --query '{Objects: Versions[].{Key:Key,VersionId:VersionId}, DeleteMarkers: DeleteMarkers[].{Key:Key,VersionId:VersionId}}')
          if [ "$versions" != "{}" ]; then
            echo "$versions" | jq -r '.Objects[] | .Key + " " + .VersionId' | while read key version_id; do
              aws s3api delete-object --bucket $bucket --key "$key" --version-id "$version_id"
            done
            echo "$versions" | jq -r '.DeleteMarkers[] | .Key + " " + .VersionId' | while read key version_id; do
              aws s3api delete-object --bucket $bucket --key "$key" --version-id "$version_id"
            done
          fi
          # Delete the bucket
          if aws s3 rb s3://$bucket --force 2>/dev/null; then
            echo "Successfully deleted bucket $bucket"
          else
            echo "Failed to delete bucket $bucket"
          fi
        done

    - name: Wipe RDS Instances
      run: |
        echo "Deleting RDS instances..."
        rds_instances=$(aws rds describe-db-instances --query 'DBInstances[*].[DBInstanceIdentifier]' --output text)
        for instance in $rds_instances; do
          aws rds delete-db-instance --db-instance-identifier $instance --skip-final-snapshot
        done

    - name: Wipe ECS Clusters
      run: |
        echo "Deleting ECS clusters, services, and tasks..."
        clusters=$(aws ecs list-clusters --query 'clusterArns[]' --output text)
        for cluster in $clusters; do
          echo "Processing cluster: $cluster"
          
          # List and stop all tasks
          tasks=$(aws ecs list-tasks --cluster $cluster --query 'taskArns[]' --output text)
          if [ -n "$tasks" ]; then
            echo "Stopping tasks in cluster $cluster"
            for task in $tasks; do
              if ! aws ecs stop-task --cluster $cluster --task $task > /dev/null 2>&1; then
                echo "Failed to stop task $task in cluster $cluster"
              fi
            done
            
            echo "Waiting for tasks to stop..."
            aws ecs wait tasks-stopped --cluster $cluster --tasks $tasks
          else
            echo "No tasks found in cluster $cluster"
          fi
          
          # List and delete all services
          services=$(aws ecs list-services --cluster $cluster --query 'serviceArns[]' --output text)
          if [ -n "$services" ]; then
            echo "Deleting services in cluster $cluster"
            for service in $services; do
              if ! aws ecs update-service --cluster $cluster --service $service --desired-count 0 > /dev/null 2>&1; then
                echo "Failed to update service $service in cluster $cluster"
              fi
              if ! aws ecs delete-service --cluster $cluster --service $service --force > /dev/null 2>&1; then
                echo "Failed to delete service $service in cluster $cluster"
              fi
            done
          else
            echo "No services found in cluster $cluster"
          fi
          
          # Delete the cluster
          echo "Deleting cluster $cluster"
          if ! aws ecs delete-cluster --cluster $cluster > /dev/null 2>&1; then
            echo "Failed to delete cluster $cluster"
          fi
        done

    - name: Wipe ECR Repositories
      run: |
        echo "Deleting ECR repositories..."
        repos=$(aws ecr describe-repositories --query 'repositories[*].[repositoryName]' --output text)
        for repo in $repos; do
          aws ecr delete-repository --repository-name $repo --force
        done

    - name: Final Message
      run: |
        echo "AWS resource wipe completed."
        echo "All resources created by these workflows should now be deleted, except for any security groups with dependencies."
        echo "If you encounter any issues or find remaining resources, please investigate and delete them manually."
        echo "You can now use your Terraform configurations to rebuild the infrastructure from scratch if needed."
