name: Wipe AWS Resources

on:
  workflow_dispatch:

jobs:
  wipe:
    name: Wipe AWS Resources
    runs-on: ubuntu-latest
    environment: development
    env:
      TF_VAR_aws_region: af-south-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
          fi

      - name: Print environment variables
        run: |
          echo "GitHub Ref: ${{ github.ref }}"
          echo "Environment: ${{ env.ENVIRONMENT }}"
          echo "AWS Region: ${{ env.TF_VAR_aws_region }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TF_VAR_aws_region }}

      - name: Verify AWS CLI Configuration
        run: |
          aws sts get-caller-identity
          aws configure list

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init and Workspace Selection
        run: |
          cd terraform
          terraform init
          terraform workspace select ${{ env.ENVIRONMENT }} || terraform workspace new ${{ env.ENVIRONMENT }}

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve -var="create_resources=false"

      - name: Wipe Orphaned Resources
        run: |
          cd terraform

          # Function to get all AWS resources with our project tag
          get_aws_resources() {
            local resource_type=$1
            aws $resource_type describe-${resource_type}s --query "${resource_type}s[?Tags[?Key=='Project' && Value=='CredEx']].${resource_type}Id" --output text
          }

          # Function to remove a resource
          remove_resource() {
            local resource_type=$1
            local resource_id=$2
            aws $resource_type delete-${resource_type} --${resource_type}-id $resource_id
            echo "Removed $resource_type: $resource_id"
          }

          # Wipe process for each resource type
          wipe() {
            local resource_type=$1
            echo "Identifying orphaned $resource_type resources..."
            orphaned_resources=$(get_aws_resources $resource_type)
            
            if [ -z "$orphaned_resources" ]; then
              echo "No orphaned $resource_type resources found."
            else
              echo "The following orphaned $resource_type resources were found:"
              echo "$orphaned_resources"
              
              for resource in $orphaned_resources; do
                remove_resource $resource_type $resource
              done
            fi
          }

          # Run wipe for different resource types
          wipe "instance"
          wipe "security-group"
          wipe "vpc"
          wipe "subnet"
          wipe "load-balancer"
          wipe "ecs-cluster"
          wipe "ecs-service"

      - name: Verify Wipe
        run: |
          cd terraform
          if terraform show; then
            echo "Error: Resources still exist after wipe"
            exit 1
          else
            echo "All resources have been successfully removed"
          fi

      - name: Log Wipe
        if: success()
        run: |
          echo "Wipe of ${{ env.ENVIRONMENT }} environment completed successfully at $(date)"

      - name: Notify on Failure
        if: failure()
        run: |
          echo "Wipe of ${{ env.ENVIRONMENT }} environment failed. Please check the logs for more information."
