name: Wipe AWS Resources

on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print GitHub context
        run: echo '${{ toJson(github) }}'

      - name: List files
        run: ls -R

      - name: Print environment variables
        run: env

      - name: Check AWS CLI
        run: aws --version

      - name: Check Terraform
        run: terraform --version
