name: Wipe AWS Resources

on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug Workflow
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_region: af-south-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print GitHub context
        run: echo '${{ toJson(github) }}'

      - name: Set environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
          fi

      - name: Print environment variables
        run: |
          echo "GitHub Ref: ${{ github.ref }}"
          echo "Environment: ${{ env.ENVIRONMENT }}"
          echo "AWS Region: ${{ env.TF_VAR_aws_region }}"

      - name: Check secret availability
        run: |
          echo "AWS_ACCESS_KEY availability: ${{ secrets.AWS_ACCESS_KEY != '' }}"
          echo "AWS_SECRET_ACCESS_KEY availability: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TF_VAR_aws_region }}

      - name: Verify AWS CLI Configuration
        run: |
          aws sts get-caller-identity
          aws configure list
